caseType: CASE_TYPE
services:
  authProvider:
    url: SERVICE_AUTH_PROVIDER_URL
    secret: SERVICE_AUTH_SECRET
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    clientSecret: IDAM_SECRET
    caching: IDAM_TOKEN_CACHE
  case:
    url: CCD_URL
    checkDivCases: SKIP_DIV_CASE_CHECK
  payments:
    url: PAYMENTS_API_URL
  fees:
    url: FEES_API_URL
  caseDocumentManagement:
    url: CASE_DOCUMENT_MANAGEMENT_URL
  equalityAndDiversity:
    url: EQUALITY_URL
    tokenKey: PCQ_TOKEN
  decreeNisi:
    url: DECREE_NISI_URL
port: PORT
session:
  redis:
    host: REDIS_HOST
e2e:
  userTestPassword: TEST_PASSWORD
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
webchat:
  avayaUrl: WEBCHAT_AVAYA_URL
  avayaClientUrl: WEBCHAT_AVAYA_CLIENT_URL
  avayaService: WEBCHAT_AVAYA_SERVICE
